#!/bin/sh

set -e

FLECTRA_CONFIGURATION_FILE=/etc/sleektiv/sleektiv.conf
FLECTRA_GROUP="sleektiv"
FLECTRA_DATA_DIR=/var/lib/sleektiv
FLECTRA_LOG_DIR=/var/log/sleektiv
FLECTRA_USER="sleektiv"

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^sleektiv:"; then
            adduser --system --home $FLECTRA_DATA_DIR --quiet --group $FLECTRA_USER
            # Data dir
            chown $FLECTRA_USER:$FLECTRA_GROUP $FLECTRA_DATA_DIR
        fi
        # Register "$FLECTRA_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $FLECTRA_USER" 2> /dev/null || true
        # Configuration file
        chown $FLECTRA_USER:$FLECTRA_GROUP $FLECTRA_CONFIGURATION_FILE
        chmod 0640 $FLECTRA_CONFIGURATION_FILE
        # Log
        mkdir -p $FLECTRA_LOG_DIR
        chown $FLECTRA_USER:$FLECTRA_GROUP $FLECTRA_LOG_DIR
        chmod 0750 $FLECTRA_LOG_DIR
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
